-- https://stackoverflow.com/questions/7686334/whats-the-recommended-location-for-sql-ddl-scripts
-- https://www.mysqltutorial.org/mysql-on-delete-cascade/
-- http://www.h2database.com/html/datatypes.html : H2 data types and Java counterparts

CREATE TABLE IF NOT EXISTS orders
(
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 MAXVALUE 99999 INCREMENT BY 1 NOCACHE NOCYCLE),
  name VARCHAR2(15)
);

ALTER TABLE orders ADD CONSTRAINT orders_pk PRIMARY KEY ( id);
ALTER TABLE orders ADD CONSTRAINT orders_name_uk UNIQUE ( name);

-- DROP SEQUENCE orders_id_seq;

--CREATE SEQUENCE orders_id_seq
-- START WITH   1
-- MAXVALUE     99999
-- INCREMENT BY 1
-- NOCACHE
-- NOCYCLE;

CREATE TABLE IF NOT EXISTS items
(
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 MAXVALUE 99999 INCREMENT BY 1 NOCACHE NOCYCLE),
  name VARCHAR2(15)
);

--DROP SEQUENCE items_id_seq;
--
--CREATE SEQUENCE items_id_seq
-- START WITH   1
-- MAXVALUE     99999
-- INCREMENT BY 1
-- NOCACHE
-- NOCYCLE;

ALTER TABLE items ADD CONSTRAINT items_pk PRIMARY KEY ( id);
ALTER TABLE items ADD CONSTRAINT items_name_uk UNIQUE ( name);

CREATE TABLE items_in_orders
(
  order_id INTEGER,
  item_id  INTEGER,
  amount   NUMBER(5)
);

-- ALTER TABLE items_in_orders ADD CONSTRAINT items_in_orders_pk PRIMARY KEY ( order_id, item_id); -- probably not necessary/bullshit anyway
ALTER TABLE items_in_orders ADD CONSTRAINT items_in_orders_order_fk FOREIGN KEY ( order_id) REFERENCES orders( id) ON DELETE CASCADE;
ALTER TABLE items_in_orders ADD CONSTRAINT items_in_orders_items_fk FOREIGN KEY ( item_id) REFERENCES items( id);
